version: 2.1

executors:
  windows-sdk:
    machine:
      image: windows-server-2019-vs2019:stable
    resource_class: windows.medium

jobs:
  build:
    executor: windows-sdk
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: |
            choco install -y qt5-base yasm curl openssl nsis wixtoolset 7zip
            curl -L -o sdl.zip http://www.libsdl.org/release/SDL-devel-1.2.15-VC.zip
            7z x sdl.zip -o"C:\SDL"
      - run:
          name: "Create LocalConfig.kmk"
          command: |
            echo VBOX_WITH_QT5_VERSION_MSG="5.15.2" > LocalConfig.kmk
            echo VBOX_WITH_QT5_PATH="C:\\Qt\\5.15.2\\msvc2019_64" >> LocalConfig.kmk
            echo VBOX_WITH_SDL_PATH="C:\\SDL\\SDL-1.2.15" >> LocalConfig.kmk
            echo VBOX_WITH_CURL_PATH="C:\\ProgramData\\chocolatey\\lib\\curl\\tools" >> LocalConfig.kmk
            echo VBOX_WITH_OPENSSL_PATH="C:\\ProgramData\\chocolatey\\lib\\openssl\\tools" >> LocalConfig.kmk
            echo VBOX_WITH_WIX_PATH="C:\\Program Files (x86)\\WiX Toolset v3.11\\bin" >> LocalConfig.kmk
            echo VBOX_PATH_NSIS="C:\\Program Files (x86)\\NSIS" >> LocalConfig.kmk
      - run:
          name: "Configure and Build"
          command: |
            cscript configure.vbs --with-sdk="C:\Program Files (x86)\Windows Kits\10" --with-wdk="C:\Program Files (x86)\Windows Kits\10"
            cmd.exe /c "env.bat && kmk"
      - run:
          name: "Package VirtualBox"
          command: |
            cmd.exe /c "env.bat && kmk packing"

workflows:
  build-virtualbox:
    jobs:
      - build